### ISSUE TITLE
MailchimpAppModel::call() should always return $this->response unless there is an error

### ISSUE THREAD

**Issue by damusnet** [dereuromark/cakephp-mailchimp#6]
Returning `false` in [MailchimpAppModel::call()](https://github.com/dereuromark/cakephp-mailchimp/blob/master/Model/MailchimpAppModel.php#L65) is problematic: the `campaignCreate` function returns an array with `[..., 'status' => 'save', ...]` when successful for example. So it succeeds, but because it has a `status` key, it still returns `false` although you then need the campaign id to send it. Maybe it should return `$this->response` anyway all the time as a last resort? I don't know enough how other functions normally react to decide on the best course of action.

**Comment by dereuromark** [comment]
is status "save" the success status? Then we could check on that instead.

**Comment by damusnet** [comment]
In this particular case, yes, but I think that is an exception rather than the rule. The `campaignSend` function returns `['complete' => true]` when successful for instance...

The only thing that seems consistent across the API are errors which have a `['status' => 'error']` response.

Also, not sure what [$this->settings['exceptions']](https://github.com/dereuromark/cakephp-mailchimp/blob/master/Model/MailchimpAppModel.php#L49) is supposed to do...

**Comment by dereuromark** [comment]
Then it throws exceptions (as the default in 3.x would be) instead of just returning bool false etc.

**Comment by damusnet** [comment]
Then this should be the default. In other words, throw an exception if it knows there is an error for sure, or return the response in any other case. Returning false is useless for debugging.

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-mailchimp/pull/8
Thank you!
